name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.5.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^0.14.0+2
  cupertino_icons: null
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flutter_sheet_localization: ^1.0.0
  flutter_week_view: ^1.0.0+2
  get: ^3.17.1
  get_storage: ^1.3.2
  json_annotation: ^3.1.1
  simple_gravatar: null
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  flutter_sheet_localization_generator: ^1.0.0
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
